name: Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: misakano7545
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/snake.svg assets/snake-dark.svg
          git diff --staged --quiet || git commit -m "chore: update contribution snake"
          git push
